[package]
name = "image-management"
version = "0.1.0"
authors = ["Tim Bikbaev <t.bikbaev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docker = "0.0.41"
